### ISSUE TITLE
[Bug]: meta list, counterstrikesharp doesnt appear. instead i see "NOFILE"

### ISSUE THREAD

**Issue by ALegitCookie** [kus/cs2-modded-server#52]
### Server is up to date

- [X] My server is up-to-date and I'm using the latest version of this mod from this github.

### I've followed the instructions

- [X] I've followed the instructions

### Game Server Login Token

- [X] I'm using a valid Game Server Login Token or running on LAN

### Operating System

Windows Server 2019

### Which mod are you playing

Surf

### Are you trying to host online or on LAN?

Online off a machine on my local network

### Metamod:Source Version

2.0.0-dev+1282

### Metamod:Source Plugins loaded

 [01] <NOFILE>

### CounterStrikeSharp Version

Unknown command 'css'!

### CounterStrikeSharp Plugins loaded

Unknown command 'css_plugins'!

### What is the bug

fresh install on windows, went through the entire setup process. when i type in "meta list", counterstrike sharp does not appear. it says the following:
 Listing 1 plugin:
  [01] <NOFILE>

Does anyone know how to fix this? I installed windows runtime to make sure it wasn't missing and it didnt fix it.

### Steps to reproduce

1. start server
2. type "meta list"

**Comment by ALegitCookie** [comment]
ended up resinstalling cssharp it's okay now

**Comment by kus** [comment]
Hey @ALegitCookie thanks for bringing this to my attention, I know you fixed it by reinstalling CCSharp but you shouldn't have to do that. I've identified the problem and fixed it.

I did a bunch of updates to the `win.bat` script and updated the [Windows install instructions](https://github.com/kus/cs2-modded-server?tab=readme-ov-file#running-on-windows) too to make them clearer.

**Comment by imperfectul1** [comment]
i have the same problem Unknown command 'css_plugins'!) , but on linux ... idk how to fix really

**Comment by lux01sv** [comment]
> i have the same problem Unknown command 'css_plugins'!) , but on linux ... idk how to fix really

Same +1
